name: Account Service CD
on:
   pull_request:
    branches:
      - "main"
    types:
      - closed

permissions:
  id-token: write
  contents: read

# cancel previous running workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  PathFilter:
   runs-on: self-hosted
    # For pull requests, it's not necessary to checkout code
   permissions:
      pull-requests: read
   outputs:
      account: ${{ steps.filter.outputs.account }}
      app: ${{ steps.filter.outputs.app }}
   steps:
   - uses: dorny/paths-filter@v2
     id: filter
     with:
       filters: |
          app:
            - 'services/app-service/**'
          account:
            - 'services/account-service/**'

  account-CD:
    needs: PathFilter
    if: ${{ needs.PathFilter.outputs.account == 'true' }} 
    uses: xebia-devops-practice/github-pipeline-library/.github/workflows/cd-pipeline.yml@main
    with:
      projectname: account-service
      targeturl: ""
    secrets: inherit # secrets can be inherited in the same organization or enterprise 

  AppService-CD:
    needs: PathFilter
    if: ${{ needs.PathFilter.outputs.app == 'true' }} 
    uses: xebia-devops-practice/github-pipeline-library/.github/workflows/cd-pipeline.yml@main
    with:
      projectname: app-service
      targeturl: ""
    secrets: inherit # secrets can be inherited in the same organization or enterprise 
